### ISSUE TITLE
נושא ראשון לנסיון

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor_android#1]
תוכן נושא לניסיון

![image](https://user-images.githubusercontent.com/6491631/28354755-bfa9b9b4-6c69-11e7-8f88-13399025ddce.png)

**Comment by dordorcomp** [comment]
היי נתן,
אני מחובר אפשר להתחיל בתהליך.

**Comment by natan1957** [comment]
האם אתה מקבל את ההודעה הזאת גם למייל?

נשלח מה-iPhone שלי

‫ב-24 ביולי 2017, בשעה 10:30, ‏‏dordorcomp ‏<notifications@github.com> כתב/ה:‬

**Comment by natan1957** [comment]
אז השיטה היא כזו:
אני פותח נושא, מצמיד תגית תקלה (בדרך כלל) ותגית של תחום התקלה.
לאחר שאתם מטפלים, אתם רושמים בכמה מילים את מהות התיקון, מצמידים תגית טופל+גרסה ושולחים.
אני בודק.
אם תוקן, אני סוגר.
אם עדיין לא תוקן, אני מוריד את התגית טופל+ גרסה ורושם מה לא תקין.
וחוזר חלילה עד שתוקן ונסגר.
אתם יכולים לשאול ולהתכתב בנוגע לתקלה.
אתם לא סוגרים תקלות גם אם לפי דעתכם זה תוקן.

הואיל והתמיכה באנגלית לא משהו.. כותבים רק בעברית. אם רוצים לכתוב משהו ב
English
פותחים לטובת זה שורה חדשה.
אפשר לכתוב בעברית איקון ולא חייבים לכתוב
icon.
זו כל התורה.

תכתוב שקיבלת והבנת.
תוסיף תגית טופל+גרסה

**Comment by dordorcomp** [comment]
יכול להגיב. :+1:

**Comment by natan1957** [comment]
ניסיון
