### ISSUE TITLE
מעבר להצגת הקלטות

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor_android#23]
לחיצה באזור החיצים לא מגיב. רק על הכיתוב.
לחיצה על החץ הימני כשהוא למעלה (באנגלית) מעבירה לשיעור עצמו.
![image](https://user-images.githubusercontent.com/6491631/29115974-14f64a42-7d02-11e7-8637-9c23ef3f2d2d.png)

**Comment by dordorcomp** [comment]
בוצע
