### ISSUE TITLE
טקסטים שונים בכותרת בחירת עולמות

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor_android#5]
איך יש טקסטים שונים  בכותרת?
![image](https://user-images.githubusercontent.com/6491631/28573027-d43a0aae-7151-11e7-991a-5c2f19ef3e88.png)
![image](https://user-images.githubusercontent.com/6491631/28573061-f467f002-7151-11e7-8206-b24f5d325004.png)

**Comment by dordorcomp** [comment]
בוצע
