### ISSUE TITLE
כפתור פאוז

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor_android#8]
כפתור הפאוז מחזיר בכל מקרה לתחילת השלב.
 בפועל הוא צריך לעצור את ההשמעה ולהמשיך אותה מאותה נקודה בלחיצה נוספת.
החזרה לתחילת השלב (בפאוז) צריכה לקרות רק בשלבים שכוללים הקלטה. כי אי אפשר להמשיך הקלטה מהנקודה שנעצרה. השמעה, ניתן.

**Comment by dordorcomp** [comment]
pause works as expected

**Comment by natan1957** [comment]
בלחיצה על פליי אחרי פאוז בשלב הקשב לשנינו, הוא לא משמיע את ההמשך.

**Comment by dordorcomp** [comment]
בוצע
